### PR TITLE
Index a trivial program

### PR DESCRIPTION
**Pull request by virgil-serbanuta**
The commented rules have no tests yet. I plan to add tests and uncomment them.

The indexing configuration may change and become more complex, but this is a fairly simple thing that would probably work.

### CODE REVIEW

**Comment by ACassimiro** [comment]
@virgil-serbanuta just as a sanity check, I'm trying to run `make build` but I'm getting the following error:

```
> make build
$(which kompile) rust-semantics/rust.md -o .build/rust-kompiled
[Error] Internal: Could not compute least upper bound for rewrite sort.
Possible candidates: [MInt{16}, MInt{64}, MInt{8}, MInt{32}]
  while executing phase "Add sort injections"
make: *** [Makefile:32: .build/rust-kompiled/timestamp] Error 113
```

Is this related to my K version? Or am I missing any steps that I should do prior to building the project?

**Comment by virgil-serbanuta** [comment]
> @virgil-serbanuta just as a sanity check, I'm trying to run `make build` but I'm getting the following error:
> 
> ```
> > make build
> $(which kompile) rust-semantics/rust.md -o .build/rust-kompiled
> [Error] Internal: Could not compute least upper bound for rewrite sort.
> Possible candidates: [MInt{16}, MInt{64}, MInt{8}, MInt{32}]
>   while executing phase "Add sort injections"
> make: *** [Makefile:32: .build/rust-kompiled/timestamp] Error 113
> ```
> 
> Is this related to my K version? Or am I missing any steps that I should do prior to building the project?

My guess is that your K needs to be past this commit: https://github.com/runtimeverification/k/commit/7e2efddff4396da9e3840feebba8d824588bfef4

I only checked version 7.1.104, which works for me.

**Review by yanliu18 — APPROVED** [review]
The implementation looks fine for me.

However, it will be nice if there is a write up about the purpose of this indexing?

Besides, it will also be good to give references of why this implementation make sense, if there is a reference. 
For example, is this [`Traits` section of rust-lang reference](https://doc.rust-lang.org/reference/items/traits.html) used?

**Comment by virgil-serbanuta** [comment]
Ok, I'll try adding some documentation.

**Pull request merged**
